import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/widgets/glass_card.dart';
import '../../../../core/widgets/gradient_text.dart';
import '../../../../data/hive/hive_initializer.dart';
import '../../data/models/forecast_model.dart';
import '../../../inventory/data/models/product_model.dart';

class ForecastScreen extends StatelessWidget {
  const ForecastScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final forecastBox = Hive.box<ForecastModel>(HiveBoxes.forecasts);
    final productsBox = Hive.box<ProductModel>(HiveBoxes.products);
    final forecasts = forecastBox.values.toList()
      ..sort((a, b) => b.generatedAt.compareTo(a.generatedAt));

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: const Text('🔮 Demand Forecast'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_rounded),
          onPressed: () => context.pop(),
        ),
      ),
      body: forecasts.isEmpty
          ? Center(
              child: Padding(
                padding: const EdgeInsets.all(32),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Text('🔮', style: TextStyle(fontSize: 64)),
                    const SizedBox(height: 24),
                    const GradientText(
                      'AI Demand Forecasting',
                      style: TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'No forecasts yet. Use the AI Chat to generate\n'
                      'demand forecasts for your products.',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        color: AppColors.textSecondary,
                        height: 1.5,
                      ),
                    ),
                    const SizedBox(height: 24),
                    OutlinedButton.icon(
                      icon: const Icon(Icons.smart_toy_rounded),
                      label: const Text('Ask AI'),
                      onPressed: () => context.go('/ai-chat'),
                    ),
                  ],
                ),
              ),
            )
          : ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: forecasts.length,
              itemBuilder: (_, i) {
                final f = forecasts[i];
                final product = productsBox.get(f.productId);
                return Padding(
                  padding: const EdgeInsets.only(bottom: 12),
                  child: GlassCard(
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            _TrendIcon(f.trendDirection),
                            const SizedBox(width: 10),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    product?.name ?? 'Unknown Product',
                                    style: TextStyle(
                                      fontSize: 15,
                                      fontWeight: FontWeight.w600,
                                      color: AppColors.textPrimary,
                                    ),
                                  ),
                                  Text(
                                    'Generated by ${f.generatedBy}',
                                    style: TextStyle(
                                      fontSize: 11,
                                      color: AppColors.textTertiary,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              padding: const EdgeInsets.symmetric(
                                horizontal: 8, vertical: 4,
                              ),
                              decoration: BoxDecoration(
                                color: AppColors.info.withValues(alpha: 0.15),
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: Text(
                                '${(f.confidence * 100).toStringAsFixed(0)}%',
                                style: TextStyle(
                                  fontSize: 12,
                                  fontWeight: FontWeight.w700,
                                  color: AppColors.info,
                                ),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),
                        Text(
                          f.recommendation,
                          style: TextStyle(
                            fontSize: 13,
                            color: AppColors.textSecondary,
                            height: 1.4,
                          ),
                        ),
                        if (f.predictedDemand.isNotEmpty) ...[
                          const SizedBox(height: 12),
                          SizedBox(
                            height: 60,
                            child: _MiniChart(data: f.predictedDemand),
                          ),
                        ],
                        const SizedBox(height: 8),
                        Text(
                          '${f.generatedAt.day}/${f.generatedAt.month}/${f.generatedAt.year}',
                          style: TextStyle(
                            fontSize: 10,
                            color: AppColors.textTertiary,
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
    );
  }
}

class _TrendIcon extends StatelessWidget {
  final String direction;
  const _TrendIcon(this.direction);

  @override
  Widget build(BuildContext context) {
    IconData icon;
    Color color;

    switch (direction.toUpperCase()) {
      case 'UP':
        icon = Icons.trending_up_rounded;
        color = AppColors.success;
        break;
      case 'DOWN':
        icon = Icons.trending_down_rounded;
        color = AppColors.error;
        break;
      default:
        icon = Icons.trending_flat_rounded;
        color = AppColors.warning;
    }

    return Container(
      width: 40,
      height: 40,
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.15),
        borderRadius: BorderRadius.circular(10),
      ),
      child: Icon(icon, color: color, size: 22),
    );
  }
}

class _MiniChart extends StatelessWidget {
  final List<double> data;
  const _MiniChart({required this.data});

  @override
  Widget build(BuildContext context) {
    if (data.isEmpty) return const SizedBox.shrink();
    final max = data.reduce((a, b) => a > b ? a : b);
    if (max == 0) return const SizedBox.shrink();

    return CustomPaint(
      size: const Size(double.infinity, 60),
      painter: _ChartPainter(data, max),
    );
  }
}

class _ChartPainter extends CustomPainter {
  final List<double> data;
  final double max;
  _ChartPainter(this.data, this.max);

  @override
  void paint(Canvas canvas, Size size) {
    if (data.length < 2) return;

    final paint = Paint()
      ..color = AppColors.primaryGradientStart
      ..strokeWidth = 2
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.round;

    final path = Path();
    final dx = size.width / (data.length - 1);

    for (int i = 0; i < data.length; i++) {
      final x = i * dx;
      final y = size.height - (data[i] / max) * size.height;
      if (i == 0) {
        path.moveTo(x, y);
      } else {
        path.lineTo(x, y);
      }
    }
    canvas.drawPath(path, paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}
